#!/usr/bin/env node
// Public strategic map: committed structure plus a REST-only GitHub status overlay.
// It intentionally has no Project-v2 or board-manager dependency.

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { buildRoadmapIndex, capabilityArchitecture, contractRequirements, evidenceReview, issueRef, issueUrl, pipelineLayout, validateRoadmap } from "../docs/strategy/roadmap-model.mjs";

const OWNER = process.env.SRS_ROADMAP_OWNER || "the-greenman";
const SCRIPT_DIR = dirname(new URL(import.meta.url).pathname);
const MODEL_PATH = resolve(SCRIPT_DIR, "../docs/strategy/roadmap.json");
const MARKDOWN_PATH = resolve(SCRIPT_DIR, "../docs/strategy/roadmap.md");

function issueLink(ref) { return `[#${issueRef(ref).number}](${issueUrl(ref, OWNER)})`; }
function cell(value) { return String(value).replaceAll("|", "\\|").replaceAll("\n", " "); }
function id(value) { return String(value).replace(/[^A-Za-z0-9_]/g, "_"); }
function mermaid(value) { return String(value).replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("[", "(").replaceAll("]", ")").replace(/\r?\n/g, "<br/>"); }
function sourceLink(source) {
  const ref = typeof source === "string" ? source : source.ref;
  if (ref.startsWith("http")) return `[${ref}](${ref})`;
  const href = ref.startsWith("docs/") ? `../${ref.slice(5)}` : `../../${ref}`;
  return `[${ref.split("/").at(-1)}](${href})`;
}

function model(path = MODEL_PATH) { return JSON.parse(readFileSync(path, "utf8")); }

function renderRoadmap(data) {
  const check = validateRoadmap(data);
  if (check.errors.length) throw new Error(`roadmap invalid:\n- ${check.errors.join("\n- ")}`);
  const index = buildRoadmapIndex(data);
  const lines = [
    "# SRS strategic map", "",
    "> Generated from `roadmap.json` by `node scripts/roadmap.mjs --write`. Do not edit this file directly.", "",
    data.purpose, "",
    `> Source status: ${data.bootstrapStatus}`, "",
    "## Mission and roadmap constitution", "",
    `**Current direction:** Ratified on ${data.mission.ratifiedOn}.`, "",
    `> ${data.mission.purpose}`, "",
    `**μDemocracy:** ${data.mission.muDemocracy}`, "",
    `**SRS:** ${data.mission.srs}`, "",
    "## First usable application", "",
    `**${data.applicationStrategy.name}** — ${data.applicationStrategy.role}`, "",
    `**Architecture:** ${data.applicationStrategy.architecture}`, "",
    "### Boundary rules", "",
    ...data.applicationStrategy.boundaries.flatMap((boundary) => [`- ${boundary}`, ""]),
    "### Modes over the shared substrate", "",
    ...data.applicationStrategy.modes.flatMap((mode) => [`- ${mode.name}`, ""]),
    "### Origin prototype", "",
    data.applicationStrategy.predecessor, "",
    "### Human–AI constitution", "",
    `> ${data.mission.humanAiConstitution}`, "",
    "### Roadmap test", "",
    "Every boundary and gate task is judged against these questions:", "",
    ...data.mission.roadmapTests.flatMap((test, index) => [`${index + 1}. ${test}`, ""]),
    "## Two release tracks", "", "```mermaid", "flowchart LR"
  ];
  for (const track of data.tracks) {
    lines.push(`  subgraph ${track.id}["${mermaid(track.name)}"]`);
    for (const boundary of data.boundaries.filter((item) => item.track === track.id)) lines.push(`    ${boundary.id}["${mermaid(`${boundary.id}: ${boundary.name}`)}"]`);
    lines.push("  end");
  }
  for (const boundary of data.boundaries) for (const required of index.targets(boundary.id, "depends-on")) lines.push(`  ${required} --> ${boundary.id}`);
  lines.push("```", "", "F2 is the first concentrated post-kernel effort. P1 and P2 may progress after F1; P3 requires both F2 and P2.", "");
  for (const track of data.tracks) {
    lines.push(`## ${track.name}`, "", track.purpose, "");
    for (const boundary of data.boundaries.filter((item) => item.track === track.id)) {
      lines.push(`### ${boundary.id} — ${boundary.name}`, "", `**Actor:** ${boundary.actor}`, "", `**Promise:** ${boundary.promise}`, "", `**Durable artifact:** ${boundary.durableArtifact}`, "", `**Entry criteria:** ${boundary.entryCriteria.join("; ")}`, "", `**Included capabilities:** ${boundary.includedCapabilities.join(", ")}`, "", `**Explicit exclusions:** ${boundary.exclusions.join("; ")}`, "", `**End-to-end walkthrough:** ${boundary.walkthrough}`, "", `**Compatibility promise:** ${boundary.compatibilityPromise}`, "", `**What becomes stable:** ${boundary.stableAfter}`, "", "| Task | Role |", "| --- | --- |");
      for (const task of boundary.tasks) lines.push(`| ${issueLink(task.ref)} | ${task.role} |`);
      if (boundary.gaps?.length) {
        lines.push("", "**Known gaps**", "", "| Gap | Owner | Activation trigger |", "| --- | --- | --- |");
        for (const gap of boundary.gaps) lines.push(`| ${cell(gap.title)} | ${cell(gap.owner)} | ${cell(gap.trigger)} |`);
      }
      lines.push("");
    }
  }
  lines.push("## SRS capability architecture", "", data.capabilityArchitecture.purpose, "", "| Stability | Meaning |", "| --- | --- |");
  for (const stability of data.capabilityArchitecture.stability) lines.push(`| ${cell(stability.label)} | ${cell(stability.meaning)} |`);
  const renderArchitecture = (node, depth = 0) => {
    const indent = "  ".repeat(depth);
    const requirements = contractRequirements(index, node.id);
    lines.push(`${indent}- **${node.name}** — ${node.promise}`, `${indent}  - Stability: ${data.capabilityArchitecture.stability.find((item) => item.id === node.stability).label}`, `${indent}  - Required by: ${requirements.length ? requirements.map((item) => item.id).join(", ") : "future work"}`, `${indent}  - Sources: ${node.sources.map(sourceLink).join(", ")}`, `${indent}  - Not included: ${node.notIncluded.join("; ")}`);
    for (const child of index.contractChildrenById.get(node.id) || []) renderArchitecture(child, depth + 1);
  };
  for (const { node } of capabilityArchitecture(index)) renderArchitecture(node);
  lines.push("");
  lines.push("## Release contract readiness", "", "Each row is a public SRS promise required by a boundary or practice stage. Readiness is assessed separately from GitHub issue state.", "", "| Contract | Required by | Specification | Implementation | Conformance |", "| --- | --- | --- | --- | --- |");
  for (const contract of data.standardContracts) {
    const assessment = (index.assessmentsByContract.get(contract.id) || [])[0];
    const requirements = contractRequirements(index, contract.id).map((item) => item.id).join(", ") || "future";
    lines.push(`| ${cell(contract.name)} | ${cell(requirements)} | ${cell(assessment?.specification || "not assessed")} | ${cell(assessment?.implementation || "not assessed")} | ${cell(assessment?.conformance || "not assessed")} |`);
  }
  lines.push("", "## Extension register", "", "Extensions are referenced by their normative SRS Records; this register records only their roadmap role and review state.", "", "| Extension | Subject | Required by | Readiness |", "| --- | --- | --- | --- |");
  for (const contract of data.standardContracts.filter((item) => item.kind === "normative-subject")) {
    const assessment = (index.assessmentsByContract.get(contract.id) || [])[0];
    const readiness = assessment ? `${assessment.specification} / ${assessment.implementation} / ${assessment.conformance}` : "not assessed";
    lines.push(`| ${cell(contract.name)} | ${cell(contract.normativeSubject.path)} | ${cell(contractRequirements(index, contract.id).map((item) => item.id).join(", "))} | ${cell(readiness)} |`);
  }
  lines.push("");
  lines.push("## Current evidence", "", `Assessed evidence snapshot as of ${data.reality.asOf}. ${data.reality.method}`, "", "| Boundary | Proven | Partial | Planned | Prototype |", "| --- | ---: | ---: | ---: | ---: |");
  for (const boundary of data.boundaries) {
    const counts = Object.fromEntries(["proven", "partial", "planned", "prototype"].map((state) => [state, 0]));
    for (const item of index.checksByBoundary.get(boundary.id) || []) counts[item.state] += 1;
    lines.push(`| ${boundary.id} — ${cell(boundary.name)} | ${counts.proven} | ${counts.partial} | ${counts.planned} | ${counts.prototype} |`);
  }
  lines.push("");
  lines.push("## Capability paths", "", "These paths show the next semantic and procedural capability a group may need. Related work connects the map to active implementation without replacing it.", "");
  for (const pipeline of data.capabilityPipelines || []) {
    lines.push(`### ${pipeline.name}`, "", pipeline.purpose, "", "```mermaid", "flowchart LR");
    for (const stage of pipeline.stages) lines.push(`  CP_${id(pipeline.id)}_${stage.id}["${mermaid(`${stage.id}: ${stage.name}`)}"]`);
    for (const stage of pipeline.stages) for (const required of index.targets(stage.id, "depends-on")) lines.push(`  CP_${id(pipeline.id)}_${required} --> CP_${id(pipeline.id)}_${stage.id}`);
    lines.push("```");
    lines.push("", "| Stage | Capability promise | Release alignment | Activation trigger |", "| --- | --- | --- | --- |");
    for (const stage of pipeline.stages) lines.push(`| ${stage.id} — ${cell(stage.name)} | ${cell(stage.promise)} | ${cell(index.targets(stage.id, "com.semanticops.strategy/aligns-with").join(", ") || "future")} | ${cell(stage.activationTrigger)} |`);
    for (const stage of pipeline.stages) {
      const anchors = (stage.executionAnchors || []).map(issueLink).join(", ") || "None mapped yet";
      lines.push("", `#### ${stage.id} — ${stage.name}`, "", `**Group need:** ${stage.groupNeed}`, "", `**Semantic additions:** ${stage.semanticAdds.join("; ")}`, "", `**Blueprint additions:** ${stage.blueprintAdds.join("; ")}`, "", `**Does not introduce:** ${stage.doesNotIntroduce.join("; ")}`, "", `**Related work:** ${anchors}`, "");
      if (stage.research?.length) lines.push(`**Research:** ${stage.research.map((item) => `${item.takeaway} (${item.source})`).join("; ")}`, "");
    }
  }
  lines.push("## Capability map", "", "```mermaid", "flowchart LR", "  S[\"Semantic sovereignty\"]");
  for (const capability of data.capabilities) lines.push(`  S --> C_${id(capability)}["${mermaid(capability)}"]`);
  for (const epic of data.epics) {
    const epicId = `E_${id(epic.ref)}`;
    lines.push(`  ${epicId}["${mermaid(`${epic.ref}: ${epic.name}`)}"]`);
    for (const capability of epic.capabilities) lines.push(`  C_${id(capability)} -.-> ${epicId}`);
  }
  lines.push("```", "", `Delivery surfaces across all branches: ${data.deliverySurfaces.join(", ")}.`, "", "## Epic and workstream disposition", "", "| Epic | Disposition | Role | Rationale |", "| --- | --- | --- | --- |");
  for (const epic of data.epics) lines.push(`| ${issueLink(epic.ref)} ${cell(epic.name)} | ${epic.disposition} | ${cell(epic.role)} | ${cell(epic.notes)} |`);
  lines.push("", "## Use", "", "- Regenerate: `node scripts/roadmap.mjs --write`.", "- Verify generated output and local evidence targets: `node scripts/roadmap.mjs --check`.", "- Audit curated evidence and review dates: `node scripts/roadmap.mjs --audit`.", "- Overlay live GitHub state: `node scripts/roadmap.mjs --status`.", "");
  return lines.join("\n");
}

function ghJson(args) { return JSON.parse(execFileSync("gh", args, { encoding: "utf8", maxBuffer: 16 * 1024 * 1024 })); }

function githubClient() {
  const cache = new Map();
  const read = (ref) => {
    if (cache.has(ref)) return cache.get(ref);
    const { repo, number } = issueRef(ref);
    const issue = ghJson(["api", `repos/${OWNER}/${repo}/issues/${number}`]);
    const blockers = ghJson(["api", "--paginate", `repos/${OWNER}/${repo}/issues/${number}/dependencies/blocked_by`]);
    const row = { ref, state: issue.state, title: issue.title, labels: (issue.labels || []).map((label) => label.name), blockers: (blockers || []).map((item) => ({ ref: `${item.repository?.name || repo}#${item.number}`, state: item.state })) };
    cache.set(ref, row); return row;
  };
  return { read };
}

function collectStatus(data, client) {
  const refs = [...new Set(data.boundaries.flatMap((boundary) => boundary.tasks.map((task) => task.ref)))];
  const rows = new Map();
  for (const ref of refs) rows.set(ref, client.read(ref));
  return rows;
}

function closed(row) { return String(row.state).toLowerCase() === "closed"; }

function renderStatus(data, rows) {
  const lines = ["SRS owner strategic map — live overlay", "", "Only explicit mapped tasks are fetched; native sub-issue descendants are not inferred as release gates.", ""];
  for (const track of data.tracks) {
    lines.push(track.name);
    for (const boundary of data.boundaries.filter((item) => item.track === track.id)) {
      const tasks = boundary.tasks.map((task) => ({ ...task, row: rows.get(task.ref) })).filter((task) => task.row);
      const gates = tasks.filter((task) => task.role === "gate");
      const done = gates.filter((task) => closed(task.row)).length;
      const blockers = tasks.flatMap((task) => task.row.blockers.filter((blocker) => String(blocker.state).toLowerCase() === "open").map((blocker) => `${task.ref} blocked by ${blocker.ref}`));
      lines.push(`- ${boundary.id} ${boundary.name}: ${done}/${gates.length} gate task(s) closed${blockers.length ? ` · ${blockers.length} open native blocker(s)` : ""}`);
    }
    lines.push("");
  }
  lines.push(`Fetched ${rows.size} explicit task issue(s).`);
  return lines.join("\n");
}

function evidencePath(ref) {
  const roots = [resolve(SCRIPT_DIR, ".."), resolve(SCRIPT_DIR, "../.."), resolve(SCRIPT_DIR, "../../..")];
  return roots.map((root) => resolve(root, ref)).find(existsSync) || null;
}

function auditRoadmap(data, today = new Date().toISOString().slice(0, 10)) {
  const rows = [];
  for (const assessment of data.assessments || []) {
    const review = evidenceReview(assessment, today);
    for (const evidence of assessment.evidence || []) {
      const target = ["repo-path", "srs-record"].includes(evidence.type) ? evidencePath(evidence.ref) : null;
      rows.push({ check: assessment, evidence, review, result: ["repo-path", "srs-record"].includes(evidence.type) ? (target ? "verified" : "missing") : evidence.type === "command" ? "manual" : "reference", target });
    }
  }
  for (const contract of data.standardContracts || []) {
    const check = { id: contract.id, assessedAt: "", reviewBy: "" };
    for (const source of contract.sources || []) if (["repo-path", "srs-record"].includes(source.type)) {
      const target = evidencePath(source.ref);
      rows.push({ check, evidence: source, review: "current", result: target ? "verified" : "missing", target });
    }
    if (contract.normativeSubject) {
      const target = evidencePath(contract.normativeSubject.path);
      let result = target ? "verified" : "missing";
      if (target) {
        try { if (JSON.parse(readFileSync(target, "utf8")).instanceId !== contract.normativeSubject.instanceId) result = "mismatched"; }
        catch { result = "invalid"; }
      }
      rows.push({ check, evidence: { type: "srs-record", ref: contract.normativeSubject.path }, review: "current", result, target });
    }
  }
  return rows;
}

function renderAudit(data, rows) {
  const lines = ["SRS owner strategic map — curated evidence audit", "", `Evidence snapshot: ${data.reality.asOf}. Audit date: ${new Date().toISOString().slice(0, 10)}.`, ""];
  for (const row of rows) lines.push(`- [${row.result}${row.review === "current" ? "" : `; review ${row.review}`}] ${row.check.id}: ${row.evidence.type} ${row.evidence.ref}${row.target ? ` → ${row.target}` : ""}`);
  const missing = rows.filter((row) => row.result === "missing").length;
  const due = [...new Set(rows.filter((row) => row.review !== "current").map((row) => row.check.id))];
  lines.push("", `${missing} missing local evidence target(s). ${due.length} reality check(s) due for review.`);
  return lines.join("\n");
}

function run(argv) {
  const modes = ["--write", "--check", "--status", "--audit"].filter((flag) => argv.includes(flag));
  if (modes.length !== 1) throw new Error("usage: roadmap.mjs --write | --check | --status | --audit");
  const data = model();
  const check = validateRoadmap(data);
  if (check.errors.length) throw new Error(`roadmap invalid:\n- ${check.errors.join("\n- ")}`);
  if (modes[0] === "--write") { writeFileSync(MARKDOWN_PATH, renderRoadmap(data)); console.log(`wrote ${MARKDOWN_PATH}`); return; }
  if (modes[0] === "--check") {
    const actual = existsSync(MARKDOWN_PATH) ? readFileSync(MARKDOWN_PATH, "utf8") : "";
    if (actual !== renderRoadmap(data)) throw new Error("roadmap output is stale; run: node scripts/roadmap.mjs --write");
    const audit = auditRoadmap(data);
    const missing = audit.filter((row) => row.result === "missing");
    if (missing.length) throw new Error(`missing local evidence target(s): ${missing.map((row) => `${row.check.id} (${row.evidence.ref})`).join(", ")}`);
    const due = [...new Set(audit.filter((row) => row.review !== "current").map((row) => row.check.id))];
    if (due.length) console.warn(`roadmap: evidence review due for ${due.join(", ")}`);
    console.log("roadmap is current"); return;
  }
  if (modes[0] === "--audit") { console.log(renderAudit(data, auditRoadmap(data))); return; }
  console.log(renderStatus(data, collectStatus(data, githubClient())));
}

export { MODEL_PATH, MARKDOWN_PATH, issueRef, validateRoadmap, renderRoadmap, collectStatus, renderStatus, auditRoadmap, renderAudit };

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try { run(process.argv.slice(2)); }
  catch (error) { console.error(`roadmap: ${error.message}`); process.exitCode = 1; }
}
